[package]
name = "pdf-poc"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.35"
clap = { version = "4.5.4", features = ["derive"] }
comemo = "0.4.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
typst = "0.11"
typst-pdf = "0.11"
