[package]
name = "pdf-poc"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.35"
comemo = "0.4.0"
typst = { git = "https://github.com/typst/typst.git" }
typst-pdf = { git = "https://github.com/typst/typst.git" }
